#!/usr/bin/env node
/**
 * Generate `src/environments/generated.ts` from `.env`.
 *
 * `.env.example` established `NG_APP_*` as this project's convention, but Angular
 * has no built-in env-var injection and the usual plugin would be another
 * dependency to justify under CONTRIBUTING hard rule 4. A dozen lines of build
 * script is cheaper than a dependency.
 *
 * Only `NG_APP_*` keys are read, so an unrelated secret sitting in `.env` cannot
 * be swept into the bundle by accident. These are OAuth *client IDs* — public
 * identifiers used with PKCE, never secrets. If a value named *_SECRET ever
 * needs to go here, the architecture has grown a backend and something is wrong.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const ALLOWED = [
  'NG_APP_GOOGLE_CLIENT_ID',
  'NG_APP_MICROSOFT_CLIENT_ID',
  'NG_APP_OAUTH_REDIRECT_URI',
];

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (ALLOWED.includes(key)) out[key] = value;
  }
  return out;
}

let fromFile = {};
try {
  fromFile = parseEnv(await readFile('.env', 'utf8'));
} catch {
  // No .env is a normal state: cloud providers simply stay unconfigured and the
  // UI hides them. The local file provider always works.
}

const resolve = (key, fallback = '') => process.env[key] ?? fromFile[key] ?? fallback;

const config = {
  googleClientId: resolve('NG_APP_GOOGLE_CLIENT_ID'),
  microsoftClientId: resolve('NG_APP_MICROSOFT_CLIENT_ID'),
  redirectUri: resolve('NG_APP_OAUTH_REDIRECT_URI', 'http://localhost:4200/auth/callback'),
};

await mkdir('src/environments', { recursive: true });
await writeFile(
  'src/environments/generated.ts',
  `// GENERATED by scripts/generate-env.mjs — do not edit, do not commit.\n` +
    `// Regenerate with \`npm run generate:env\`.\n\n` +
    `export const oauthConfig = ${JSON.stringify(config, null, 2)} as const;\n`,
  'utf8',
);

const configured = [
  config.googleClientId && 'Google Drive',
  config.microsoftClientId && 'OneDrive',
].filter(Boolean);

console.log(
  `generate:env — wrote src/environments/generated.ts ` +
    `(${configured.length ? `configured: ${configured.join(', ')}` : 'no cloud providers configured'})`,
);
